spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,.h2.server.properties
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./target/h2db/db/customer;DB_CLOSE_DELAY=-1
    username: customer
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
server:
  port: 8081