version: '2'
services:
  customer-app:
    build:
      context: ../../../
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://customer-postgresql:5432/customer
    depends_on:
      - customer-postgresql
  customer-postgresql:
    extends:
      file: postgresql.yml
      service: customer-postgresql
