version: '2'
services:
  customer-app:
    image: customer
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://customer-postgresql:5432/customer
  customer-postgresql:
    extends:
      file: postgresql.yml
      service: customer-postgresql
